### ISSUE TITLE
A question about pertubation and pertubated features

### ISSUE THREAD

**Issue by BakerBunker** [sh-lee-prml/HierSpeechpp#18]
In Section 3.2 of the paper, it was mentioned that 
> we utilize a speech perturbation to remove speaker-related information from the self-supervised speech representation.

Which speech perturbation did you use to remove speaker-related information, is it formant shift?

And how do you get the pertubated features during training, preprocessed or on-the-fly?

**Comment by sh-lee-prml** [comment]
Hi

We utilize the speech perturbation method which is proposed in NANSY. (Formant Shifting, Pitch Randomization, Random Frequency Shaping)

We referred [this implementation](https://github.com/revsic/torch-nansy) for on-the-fly perturbation in batch. (not in data loader). 

Thanks!

**Comment by BakerBunker** [comment]
Thank you for your reply!
In torch-nansy, perturbations are made by parselmouth, which is slow in training process, and on-the-fly MMS feature extraction is slow too. 
So I wonder, in the hyperparameter settings prsented in paper, how many seconds it takes for a training step?

**Comment by sh-lee-prml** [comment]
I agree that this perturbation and MMS is slow, however, this significantly affect the performance of voice style transfer.

With on-the-fly perturbation, our entire TTS pipeline could achieve the robust TTS performance.
(Although we feed the predicted MMS features from TTV models, the hierarchical speech synthesizer could synthesize the speech robustly! because the hierarchical speech synthesizer is trained with perturbed features!)

To reduce the burden, we slice the audio for the maximum segment size of 61440 frames in data loader.

sampling rate: 16000
hop size: 320
max segment size (about 3.84 seconds): 61,440 frames (waveform level), 192 frames (MMS level).

and we perturb the speech and extract the MMS features in batches at once.

Much more specifically, for decoder, we additionally slice the segments by 9,600 frames (30 frames (hiddens) * hop size of 320).

TBH, I also think that the slow training speed for hierarchical speech synthesizer is the limitation of our works. 

In addition, we utilize too many discriminators for high-quality audio. However, this also improve the entire model performance...!

Thanks!

**Comment by BakerBunker** [comment]
Huge thanks to your detailed explanations!
