### ISSUE TITLE
Possible inconsistency between SpeechSR implementation and paper description

### ISSUE THREAD

**Issue by Edresson** [sh-lee-prml/HierSpeechpp#47]
Hi @sh-lee-prml, 

Thanks for the great work that you are doing and for making this awesome repository open-source :).

I think I might found an inconsistency between the code of the SpeechSR and the paper description. In section 3.4 of the paper is said that "We further replace a transposed convolution with nearest neighbor (NN) upsampler. Previously, an NN upsampler was shown to alleviate tonal artifacts caused by transposed convolutions. We found that the NN upsampler also reduce the error in the high spectrum compared to the transposed convolution." and in the code the linear interpolation is used instead of NN: https://github.com/sh-lee-prml/HierSpeechpp/blob/318c633cdc24cf3239d62c95ea8afae200ed2d13/speechsr48k/speechsr.py#L96C41-L96C70

I'm wondering if it is a code or description issue.  I'm trying to apply the contributions that you guys did in my own project but I'm not sure if I should use NN or linear interpolation.

Thanks very much :).

**Comment by sh-lee-prml** [comment]
Hi @Edresson 

Thanks for letting me know this issue.

There are some mistakes at the released source code and I will check the checkpoint of SpeechSR. 

First, I utilized NN Upsampler by using "nearest". However, I had mistake to upload this module. Sorry for the confusion.

Actually, linear interpolation version was utilized for 16k to 24k model...  so I will check it again.

I need to request the permission for the checkpoints I experimented to my previous lab.

Please wait a moment..!

Thanks:)

**Comment by sh-lee-prml** [comment]
Hi @Edresson 

Thanks for your patience.

First, as you said, we uploaded the linear interpolation version of speech super-resolution models in this page. 
(This is our fault. sorry for the confusion)

When we train the linear interpolation and NN version of SR with a Single GPU and VCTK dataset again (We used four GPUs for the paper results), 

The results shows that the ViSQOL of Linear version is 3.18 and
the ViSQOL of NN version is 3.27.

However, 

due to our mistake, we train the linear version of SR models with a large-scale dataset.

Thanks to the larger dataset, this model has a better performance than the VCTK models. 

If we can use the additional GPU, we will train the NN version of SR with a large-scale dataset and release it in the future!

------------
Congratulations on getting your paper(XTTS) accepted in INTERSPEECH!

and I'm really happy to receive your thanks in the Acknowledgments. 

Thanks again and Thank you for your contribution to the community.

**Comment by Edresson** [comment]
> Hi @Edresson
> 
> Thanks for your patience.
> 
> First, as you said, we uploaded the linear interpolation version of speech super-resolution models in this page. (This is our fault. sorry for the confusion)
> 
> When we train the linear interpolation and NN version of SR with a Single GPU and VCTK dataset again (We used four GPUs for the paper results),
> 
> The results shows that the ViSQOL of Linear version is 3.18 and the ViSQOL of NN version is 3.27.
> 
> However,
> 
> due to our mistake, we train the linear version of SR models with a large-scale dataset.
> 
> Thanks to the larger dataset, this model has a better performance than the VCTK models.
> 
> If we can use the additional GPU, we will train the NN version of SR with a large-scale dataset and release it in the future!

Hi @sh-lee-prml,

Thanks very much for the detailed answer :).


> Congratulations on getting your paper(XTTS) accepted in INTERSPEECH!
> 
> and I'm really happy to receive your thanks in the Acknowledgments.
> 
> Thanks again and Thank you for your contribution to the community.

Thank you for your valuable contributions to the community as well. I look forward to the opportunity to meet you in person at INTERSPEECH or another conference in the future.
